#!/bin/bash

TYPE="${1:?Provide a network type}"
case "$TYPE" in
    "wifi")
        TYPE_NAME='WIFI'
        ;;
    "ethernet")
        TYPE_NAME='ETH'
        ;;
    *)
    echo 'Wrong type'
        exit 1
        ;;
esac

INTERFACE="${instance:-_first_}"
FORMAT_UP="${format_up:-$TYPE_NAME %essid}"
FORMAT_DOWN="${format_down:-$TYPE_NAME}"

if [ "$INTERFACE" = "_first_" ]
then
  INTERFACE="$(nmcli connection show --active | grep "$TYPE" | sed -e 's/ *$//' -e 's/.* //')"
fi

essid () {
  SSID="$(nmcli connection show --active | grep "$TYPE *$INTERFACE")"
  echo "${SSID%% *}"
}

if grep -wq up "/sys/class/net/$INTERFACE/operstate"
then
  echo "$FORMAT_UP" | sed \
    -e "s,%essid,$(essid),g" \
    -e q
  echo
  echo '#00FF00'
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
