#!/bin/bash

TYPE="${1:?Provide a network type}"
case "$TYPE" in
    "wifi")
        TYPE_NAME='WIFI'
        ;;
    "ethernet")
        TYPE_NAME='ETH'
        ;;
    *)
    echo 'Wrong type'
        exit 1
        ;;
esac

INTERFACE="${instance:-_first_}"
FORMAT_UP="${format_up:-$TYPE_NAME %conn_name}"
FORMAT_DOWN="${format_down:-$TYPE_NAME}"

if [ "$INTERFACE" = "_first_" ]
then
  INTERFACE="$(nmcli connection show --active | grep "$TYPE" | sed -e 's/ *$//' -e 's/.* //')"
fi

conn_name () {
  NAME="$(nmcli connection show --active | grep "$TYPE *$INTERFACE")"
  echo "${NAME%% *}"
}

if [[ ! -z "$(conn_name)" ]]; then
  echo "$FORMAT_UP" | sed \
    -e "s,%conn_name,$(conn_name),g" \
    -e q
  echo
  echo '#FFFFFF'
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
