#!/bin/bash

FORMAT_UP="${format_up:-VPN %vpn_names}"
FORMAT_DOWN="${format_down:-VPN}"
VPNS=''
IS_WORK=0

get_vpn_names() {
  local -r NAMES=(
    $(nmcli connection show --active | grep '\bvpn\b' | cut -f1 -d ' ')
  )

  local -r last_i="$(( ${#NAMES[@]} -1 ))"
  for i in $(seq 0 "$last_i"); do
    if [[ "${NAMES[i]}" =~ WRK ]]; then
        IS_WORK=1
    fi

    VPNS+="${NAMES[i]}"

    if [[ "$i" -ne "$last_i" ]]; then
      VPNS+=', '
    fi
  done
}

get_vpn_names

if nmcli connection show --active | grep -wq vpn
then
  echo "$FORMAT_UP" | sed \
    -e "s/%vpn_names/${VPNS}/g" \
    -e q
  echo

  if [[ "$IS_WORK" -eq 1 ]]; then
    echo '#FFFF00'
  else
    echo '#00FF00'
  fi
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
