#!/bin/bash

INTERFACE="${instance:-_first_}"
FORMAT_UP="${format_up:-WIFI: %essid}"
FORMAT_DOWN="${format_down:-WIFI}"

if [ "$INTERFACE" = "_first_" ]
then
  INTERFACE="$(nmcli connection show --active | grep wifi | sed -e 's/ *$//' -e 's/.* //')"
fi

essid () {
  SSID="$(nmcli connection show --active | grep "wifi *$INTERFACE")"
  echo "${SSID%% *}"
}

if grep -wq up "/sys/class/net/$INTERFACE/operstate"
then
  echo "$FORMAT_UP" | sed \
    -e "s,%essid,$(essid),g" \
    -e q
  echo
  echo '#00FF00'
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
