#!/bin/bash

TYPE="${1:?Provide a network type}"
INTERFACE="${instance:-_first_}"
FORMAT_UP="${format_up:-${TYPE^^} %essid}"
FORMAT_DOWN="${format_down:-${TYPE^^}}"

if [ "$INTERFACE" = "_first_" ]
then
  INTERFACE="$(nmcli connection show --active | grep "$TYPE" | sed -e 's/ *$//' -e 's/.* //')"
fi

essid () {
  SSID="$(nmcli connection show --active | grep "$TYPE *$INTERFACE")"
  echo "${SSID%% *}"
}

if grep -wq up "/sys/class/net/$INTERFACE/operstate"
then
  echo "$FORMAT_UP" | sed \
    -e "s,%essid,$(essid),g" \
    -e q
  echo
  echo '#00FF00'
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
